server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
    connection-timeout: 5000ms
  port: 8080
  servlet:
    context-path: /clouddisk
spring:
  profiles:
    active: dev
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.194.103:3306/clouddisk-springboot
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  mail:
    host: smtp.qq.com
    port: 465
    username: 641484973@qq.com
    password: xgsypmurcaxubeia
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true
  redis:
    database: 0
    host: 192.168.194.103
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 2000

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

#Minio配置
minio:
  host: http://192.168.194.103:9000
  url: ${minio.host}/${minio.bucketName}
  accessKey: chiiiplow
  secretKey: chiiiplow
  bucketName: clouddisk

chiiiplow:
  clouddisk:
    jwt:
      secret: you're_never_gonna_know
      expire: 7

